name: Trigger Slave Repos to Update Workflows

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  call-workflow-passing-data:
    name: Update Slave Workflows
    uses: L-Quibiq/Slave/.github/workflows/update-workflows.yml@workflows
