name: Trigger Slave Repos to Update Workflows

# Specify the permissions for the GITHUB_TOKEN
permissions:
  contents: write  # Grants the ability to write contents (push changes)
  actions: write   # Grants the ability to trigger workflow actions

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  trigger-slaves:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Slave Repo Workflow Update
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/L-Quibiq/Slave/actions/workflows/update-workflows.yml/dispatches \
          -d '{"ref":"workflows"}'
