name: Trigger Slave Repos to Update Workflows

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  push-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Prepare folder contents
      run: |
        mkdir -p temp-directory
        cp -R .github/workflows/* temp-directory/
        cd temp-directory
        git init
        git add .
        git commit -m "Automated commit of folder contents"

    - name: Force push to Repository 2
      run: |
        git remote add repo2 https://$GITHUB_TOKEN@github.com/L-Quibiq/Slave.git
        git push --force repo2 main:workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
